name = "discite-ai"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# The Next.js output for Cloudflare Pages
# Run: npx @cloudflare/next-on-pages

[[d1_databases]]
binding = "DB"
database_name = "discite-progress"
database_id = "1f4ab6b3-2104-4718-8d06-8d088d54ac85"

compatibility_flags = ["nodejs_compat"]
